### ISSUE TITLE
api/v1/profiles - OperationalError: canceling statement due to conflict with recovery

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1140] opened 2017-10-05 07:01 UTC
https://sentry.onalabs.org/ona/onadata/issues/173/

```
OperationalError: canceling statement due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.

(17 additional frame(s) were not displayed)
...
  File "rest_framework/serializers.py", line 501, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "rest_framework/fields.py", line 1754, in to_representation
    return method(value)
  File "pricing/serializer.py", line 123, in get_user_monthly_submissions
    count_user_monthly_submission)
  File "pricing/serializer.py", line 50, in query_data
    data = function(obj.user, **kwargs)
  File "pricing/query.py", line 44, in count_user_monthly_submission
    for xform_id in queryset

OperationalError: canceling statement due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.

```

**Comment by ukanga** [comment] 2019-07-03 07:50
Duplicate of #906

**Closed by ukanga** 2019-07-03 07:50 UTC
