### ISSUE TITLE
Downloading a missing xls file triggers as exception

### ISSUE THREAD

**Issue by ivermac** [onaio/onadata#1011] opened 2017-05-03 08:32 UTC
Trying to download a missing xls file using core triggers the following error.

```python
Internal Server Error: /api/v1/forms/<formid>/form.xls

IOError at /api/v1/forms/<formid>/form.xls
File does not exist: <username>/xls/<filename>.xlsx
Traceback:

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/template/response.py" in render
  107.             self.content = self.rendered_content

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/template/response.py" in content
  137.         HttpResponse.content.fset(self, value)

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/http/response.py" in content
  329.             content = b''.join(self.make_bytes(chunk) for chunk in value)

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/http/response.py" in <genexpr>
  329.             content = b''.join(self.make_bytes(chunk) for chunk in value)

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/core/files/base.py" in __iter__
  101.         for chunk in self.chunks():

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/core/files/base.py" in chunks
  76.             self.seek(0)

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/core/files/utils.py" in <lambda>
  20.     seek = property(lambda self: self.file.seek)

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/db/models/fields/files.py" in _get_file
  52.             self._file = self.storage.open(self.name, 'rb')

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/django/core/files/storage.py" in open
  38.         return self._open(name, mode)

File /.../.virtualenvs/onadata/local/lib/python2.7/site-packages/storages/backends/s3boto.py" in _open
  394.             raise IOError('File does not exist: %s' % name)

Exception Type: IOError at /api/v1/forms/<formid>/form.xls
Exception Value: File does not exist: <username>/xls/<filename>.xlsx
```

**Comment by ukanga** [comment] 2017-06-03 07:47
duplicate of #911

**Closed by ukanga** 2017-06-03 07:47 UTC
Labels: API, Error
