### ISSUE TITLE
No error message for relevant expressions referencing future questions

### ISSUE THREAD

**Issue by bkimondiu** [onaio/onadata#1709] opened 2019-10-30 07:16 UTC
### Environment (local, stage, preview, production)
Production

### Expected behavior
When an XLSForm is authored and a question is created with a relevant expression that references a future question, an error should be returned when uploading the form to Ona.

### Actual behavior
An XLSForm authored with a question that has a relevant expression that references a future question is uploaded successfully to Ona. The question with the relevant expression is hidden when the form is launched (as expected) and shows up when the future question's response satisfies its relevant expression.

### Steps to reproduce the behavior
1. Author an XLSForm with the columns `type`, `name`, `label` and `relevant`.
2. Add two questions to the XLSForm e.g. Qn1 and Qn2
3. Add a relevant expression to Qn1 that references Qn2
4. Add the form to an Ona account

Find attached an XLSForm for testing

[future_relevant.xlsx](https://github.com/onaio/onadata/files/3787350/future_relevant.xlsx)

**Comment by ivermac** [comment] 2020-04-06 07:26
Hey @lincmba could you please comment why this is a `wontfix` before we close it?

**Comment by lincmba** [comment] 2020-08-11 08:19
@ivermac This was labeled `wontfix` because it is an expected behavior and not an error.

**Closed** 2020-08-11 08:24 UTC
Labels: Wontfix
