### ISSUE TITLE
Require Phone Authentication Radio button not being checked/selected 

### ISSUE THREAD

**Issue by katembu** [onaio/onadata#2200] opened 2022-02-22 05:25 UTC
The radio button on account setting >> Require Phone Authentication:  is not showing as checked when a user switches between "YES" and "NO" hence its difficult to tell if the setting has between changed.
**For example:** The default setting is YES(Restrict). If one clicks "NO", "NO" radio button will not be highlighted as clicked. If one proceed to save and refresh the page, now "NO" will show as selected. Toggle between the two buttons seems not working as required.

**Comment by ciremusyoka** [comment] 2022-02-23 06:16
Duplicate of https://github.com/onaio/zebra/issues/6723

**Closed** 2022-03-02 07:19 UTC
Labels: Error
